### ISSUE TITLE
Request for the dataset

### ISSUE THREAD

**Issue by HungerPWAY** [Clin0212/HydraLoRA#1]
Hello Authors,

Great work!

Could you provide the dataset directly? I’m having some difficulties running the code and I’m not sure what format the dataset should be in. Thank you!

Best regards,
Pengwei Tang

**Comment by Clin0212** [comment]
Hello Pengwei,

Thank you for your kind words and for your interest in our work.

We're happy to provide you with direct access to the datasets. Here are the links:

**For Single-Domain Datasets:**

1. **databricks-dolly-15k**: [databricks/databricks-dolly-15k](https://huggingface.co/datasets/databricks/databricks-dolly-15k)

2. **GenMedGPT**: [Download Link](https://drive.google.com/file/d/1ZKbqgYqWc7DJHs3N9TQYQVPdDQmZaClA/view)  
   **icliniq-10k**: [Download Link](https://drive.google.com/file/d/1ZKbqgYqWc7DJHs3N9TQYQVPdDQmZaClA/view)

3. **Lawyer-Instruct**: [Alignment-Lab-AI/Lawyer-Instruct](https://huggingface.co/datasets/Alignment-Lab-AI/Lawyer-Instruct)  
   **US-term**: [lexlms/legal_lama](https://huggingface.co/datasets/lexlms/legal_lama/blob/main/us_terms.jsonl)

4. **GSM8K**: [openai/gsm8k](https://huggingface.co/datasets/openai/gsm8k)

5. **CodeAlpaca-20k**: [HuggingFaceH4/CodeAlpaca_20K](https://huggingface.co/datasets/HuggingFaceH4/CodeAlpaca_20K)

**For Multi-Task Domain Dataset:**

- **Flanv2**: [lorahub/flanv2](https://huggingface.co/datasets/lorahub/flanv2)

Please note that the asymmetric structure of HydraLoRA is not limited to the datasets listed above. You're welcome to use other datasets to explore its robustness.

If you have any questions or need assistance with the dataset formats, feel free to reach out. We're here to help.

Best regards,

Chunlin

**Comment by HungerPWAY** [comment]
Thanks for your help!
