### ISSUE TITLE
What do I need to do to use the more recent model?

### ISSUE THREAD

**Issue by qychen2001** [Clin0212/HydraLoRA#11]
Very nice paper and implementation!
As the model base capabilities advance, I'd like to try this on more advanced models such as llama3 and qwen2.5, but I noticed you modified the source code for transformers. I would like to know what adjustments I need to make if I want to adapt to newer models.
Sincere thanks!

**Comment by Clin0212** [comment]
In `transformers`, we mainly modify `modeling_llama.py` to introduce a new parameter `task_types`. 

However, this is done to replicate the Baseline construction. During the training with HydraLoRA, you can set it to `None`. 

Additionally, you can disable `task_types` by directly removing the `task_types` section in `build_dataset.py`, so no modifications to the transformers code are necessary.

**Comment by qychen2001** [comment]
That's great!
This will make it easier to use the latest models, and I think you could add instructions for this in the `README.md` as well, otherwise the presence of `transformers` can make it hard to know how to adapt them.
Sincere thanks again.

**Comment by Clin0212** [comment]
Thanks for your suggestion, it's been updated in the `README.md` with notes.
