### ISSUE TITLE
What is the “% Parameter” for?

### ISSUE THREAD

**Issue by ShuDun23** [Clin0212/HydraLoRA#12]
Hi @Clin0212 , great work! I am not quite sure what "% parameter" represents in the article. Could you please tell me what "% parameter" is for?

Thanks!

**Comment by Clin0212** [comment]
Thank you for your question. The `% parameter` refers to the ratio of tunable parameters to the base model.

**Comment by ShuDun23** [comment]
Thanks

> Thank you for your question. The `% parameter` refers to the ratio of tunable parameters to the base model.
