### ISSUE TITLE
About experiment details of multi-task experiments

### ISSUE THREAD

**Issue by xcppy** [Clin0212/HydraLoRA#13]
Hi,
Thank you for your great work!
I'm reproducing your multi-task domain results on BBH benchmark in Table 3, and I have some problems that need your help. Could you please share the hyperparameters used in your experiments, like lora_rank, lora_b_nums, num_train_epochs and so on. Besides, there are multiple config files of BBH dataset, which one did you use in your experiment? 

Thanks!

**Comment by Clin0212** [comment]
Thank you for your question! As mentioned in Table 3, the hyperparameter `lora_b_nums` was set to `10`, and `lora_rank` was set to `8`. The other configurations were kept at their default values (no modifications). For the BBH dataset, you can refer to [`lorahub`](https://github.com/sail-sg/lorahub).

**Comment by xcppy** [comment]
Thanks for your answer!
