### ISSUE TITLE
Understanding of Figure 3

### ISSUE THREAD

**Issue by prion502** [Clin0212/HydraLoRA#14]
As stated in the text, a dataset is fine-tuned using multi-head LoRAs, the Dolly-15K dataset in the figure is split into three tasks,and your approach to train with a single-head LoRA for each task? Would this be equivalent to subdividing the tasks? There is no fine-tuning of one task with a multi-head LoRA. I'm not sure if I understand this correctly? And how is the LoRA split in Table1 trained? Here again, two heads are represented.

**Comment by Clin0212** [comment]
**A1:** Yes, your understanding is correct. In this case, the tasks are fine-tuned using single-head LoRA (i.e., `1A1B`), which corresponds to applying vanilla LoRA to sub-task data. The multi-head design has not been introduced at this stage.

**A2:** LoRA (Split), as proposed in the paper, is a variant where instead of using a single large LoRA, multiple smaller LoRAs (`nAnB`) with the same total number of parameters are used for fine-tuning each task. This allows for more modular and task-specific adaptation.

**Comment by prion502** [comment]
> **A1:** Yes, your understanding is correct. In this case, the tasks are fine-tuned using single-head LoRA (i.e., `1A1B`), which corresponds to applying vanilla LoRA to sub-task data. The multi-head design has not been introduced at this stage.
> 
> **A2:** LoRA (Split), as proposed in the paper, is a variant where instead of using a single large LoRA, multiple smaller LoRAs (`nAnB`) with the same total number of parameters are used for fine-tuning each task. This allows for more modular and task-specific adaptation.

When you applied the multi-head LoRA, how did you merge the features obtained from multiple heads together? If you have N heads, is the weight of each head 1/N?

**Comment by Clin0212** [comment]
Sorry, I’m not sure I fully understand your question. Are you referring to `HydraLoRA` when you mention `multi-head LoRA`? The merging process here uses MoE. You can find more details in the `design` section of the paper and the GitHub repository.

**Comment by prion502** [comment]
> Sorry, I’m not sure I fully understand your question. Are you referring to `HydraLoRA` when you mention `multi-head LoRA`? The merging process here uses MoE. You can find more details in the `design` section of the paper and the GitHub repository.

It's the (LoRA split) 16 X 2 in table1, how did you merge the features obtained from multiple heads together? If there are 2 heads, is the weight of each head 1/2?

**Comment by Clin0212** [comment]
Not directly weight averaging, the MoE method is also employed here.

**Comment by prion502** [comment]
Okay, thanks for taking the time to answer my question.
