### ISSUE TITLE
about Multi-task Domain

### ISSUE THREAD

**Issue by sunrise224** [Clin0212/HydraLoRA#15]
Thank you for your work. I would like to confirm that for Multi-task Domain, separate LoRA adapters are not assigned to each subtask. Instead, the number of adapters is initialized based on k-means, and LoRA and the router are jointly trained on the entire dataset.

**Comment by Clin0212** [comment]
Thank you for your question. Your understanding is correct. Separate LoRA adapters are not assigned to each subtask. Instead, the number of adapters is initialized based on k-means, and both LoRA and the router are jointly trained on the entire dataset.
