### ISSUE TITLE
about MMLU score

### ISSUE THREAD

**Issue by Xiaoni-61** [Clin0212/HydraLoRA#16]
Thank you for your work. 
Why did your MMLU score only 38.88 using the original llama2-7B model test? But llama website given llama2-7b scored 45.3 web site is https://www.llama.com/llama2/ I use https://github.com/percent4/llm_evaluation_4_mmlu to get the original llama2 test is almost 45 or so, also want to ask whether it can explain why is this? Or maybe you could share your evaluation code. Thank you!

**Comment by Clin0212** [comment]
Thank you for your question. Since this paper adopts `zero-shot` for MMLU, it also shows how to set up zero-shot in the code.

**Comment by Xiaoni-61** [comment]
OK thanks!
