### ISSUE TITLE
About learnable parameters

### ISSUE THREAD

**Issue by tianlwang** [Clin0212/HydraLoRA#19]
Thank you for your excellent work!

In the experimental tables(such as `Table 1`, `Table 2`), it seems that the `% Parameter` only includes the parameters of the LoRA A and LoRA B matrices? According to my understanding, the LoRA route should also be learnable. Are its parameters included in the `% Parameter`?

**Comment by Clin0212** [comment]
Thank you for your question. Indeed, the LoRA router is trainable. However, its parameters are negligible compared to the parameters of the LoRA A and B matrices.

**Comment by tianlwang** [comment]
> Thank you for your question. Indeed, the LoRA router is trainable. However, its parameters are negligible compared to the parameters of the LoRA A and B matrices.

Thank you for your response! I would like to confirm: if the model dimension is `d`, the rank of LoRA is `r`, and the number of experts (i.e., the number of `B` matrices) is `n`, would the parameters of LoRA be `(n + 1) * d * r`, and the parameters of the router be `n * d`? When `r` is relatively large, the number of parameters for the router is almost negligible.

**Comment by Clin0212** [comment]
Yes, your understanding is correct. As the rank `r` value increases, the proportion of parameters contributed by the router becomes smaller.

**Comment by tianlwang** [comment]
Okay, thanks!
