### ISSUE TITLE
the meaning of the parameter class Linear in lora.py is unknown

### ISSUE THREAD

**Issue by Xiaoni-61** [Clin0212/HydraLoRA#4]
I run fine-tune.py directly, using databricks-dolly-15k, which appears in the code (peft/tuners/lora.py) in the image below
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType',
Through debug, I find that blc_alpha parameter is not initialized (still none), and blc_weight is not initialized either. I would like to ask if there is any solution, and what do these two parameters represent
![image](https://github.com/user-attachments/assets/97584828-ee44-4d1e-8040-e7e702ba154f)

**Comment by Clin0212** [comment]
"blc_alpha" and "blc_weight" are parameters utilized in the evaluation of other baseline, mainly for adjusting factors such as weights. These parameters have been removed in [lora.py](https://github.com/Clin0212/HydraLoRA/blob/main/HydraLoRA/peft/peft/tuners/lora.py), Thank you for your question; we will continue to remove these redundant parts.
