### ISSUE TITLE
The position of the hydralora module in the model？

### ISSUE THREAD

**Issue by WonderLandxD** [Clin0212/HydraLoRA#6]
Hello, thank you for your contribution. I would like to ask if your hydralora module is parallel to each transformer module. Or is it just added to the q, v matrix in the transformer? I noticed that the style shown in your Fig. 4B seems to be calculated in parallel with each transformer module.

**Comment by Clin0212** [comment]
Thank you for your question. Fig. 4B is intended to better visualize the process of MoE in the B matrix during inference. Similar to the vanilla LoRA, HydraLoRA incorporates adapters into each linear layer within the FFN layers.

**Comment by WonderLandxD** [comment]
> Thank you for your question. Fig. 4B is intended to better visualize the process of MoE in the B matrix during inference. Similar to the vanilla LoRA, HydraLoRA incorporates adapters into each linear layer within the FFN layers.

I understand, thanks for your answer :)
