### ISSUE TITLE
Request for Sharing deepspeed_config_file 

### ISSUE THREAD

**Issue by Fandibio** [Clin0212/HydraLoRA#8]
Hello Authors,

Thank you for your great work and for sharing the code!

I am currently trying to reproduce your results and have encountered some difficulties in configuring the deepspeed_config_file. Could you kindly provide the content or specific settings of the deepspeed_config_file that you used? This would greatly help with my work and deepen my understanding.

Thank you in advance for your assistance!

**Comment by Clin0212** [comment]
Thank you for your question. You can refer to [https://www.deepspeed.ai/docs/config-json/](https://www.deepspeed.ai/docs/config-json/) for configuration. If you have sufficient GPU memory, you might not need to use DeepSpeed, as fine-tuning might be faster without it. Additionally, we have provided a reference [deepspeed_config_file](https://github.com/Clin0212/HydraLoRA/blob/main/HydraLoRA/ds_zero3_offload.json)

**Comment by tx467** [comment]
Hi! I wonder how can I change the code so that DeepSpeed is not used as you mentioned? I did not find a place to pass in the argument.

**Comment by Clin0212** [comment]
You can replace the config in [fine-tuning.sh](https://github.com/Clin0212/HydraLoRA/blob/main/HydraLoRA/fine-tuning.sh) with your configuration, i.e., `deepspeed_config_file= path_to _ur_dp_config`.

**Comment by tx467** [comment]
I see. Thank you for the information!
